default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wearables_development

test:
  <<: *default
  database: wearables_test

production:
  <<: *default
  database: wearables_production
  username: wearables
  password: <%= ENV["WEARABLES_DATABASE_PASSWORD"] %>
